// <auto-generated />
using System;
using Fithub.Platform.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fithub.Platform.Repositories.Migrations
{
    [DbContext(typeof(FithubDbContext))]
    partial class FithubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Equipment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 27, DateTimeKind.Utc).AddTicks(3316),
                            Name = "Barbell"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 27, DateTimeKind.Utc).AddTicks(4352),
                            Name = "Dumbbell"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 27, DateTimeKind.Utc).AddTicks(4355),
                            Name = "Kettlebell"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 27, DateTimeKind.Utc).AddTicks(4356),
                            Name = "Cable Machine"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 27, DateTimeKind.Utc).AddTicks(4358),
                            Name = "Resistance Band"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000006"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 27, DateTimeKind.Utc).AddTicks(4360),
                            Name = "Pull-up Bar"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000007"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 27, DateTimeKind.Utc).AddTicks(4362),
                            Name = "Bench"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000008"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 27, DateTimeKind.Utc).AddTicks(4363),
                            Name = "Bodyweight"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000009"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 27, DateTimeKind.Utc).AddTicks(4365),
                            Name = "Treadmill"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000010"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 27, DateTimeKind.Utc).AddTicks(4366),
                            Name = "Bicycle"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000011"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 27, DateTimeKind.Utc).AddTicks(4368),
                            Name = "Rowing Machine"
                        });
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.ExerciseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExerciseCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 29, DateTimeKind.Utc).AddTicks(3053),
                            Name = "Compound"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 29, DateTimeKind.Utc).AddTicks(3524),
                            Name = "Isolation"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 29, DateTimeKind.Utc).AddTicks(3526),
                            Name = "HIIT"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 29, DateTimeKind.Utc).AddTicks(3528),
                            Name = "Rehabilitation"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 29, DateTimeKind.Utc).AddTicks(3530),
                            Name = "Mobility"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 29, DateTimeKind.Utc).AddTicks(3531),
                            Name = "Powerlifting"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 29, DateTimeKind.Utc).AddTicks(3533),
                            Name = "Bodybuilding"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000008"),
                            CreatedOn = new DateTime(2026, 5, 17, 16, 21, 28, 29, DateTimeKind.Utc).AddTicks(3534),
                            Name = "Functional"
                        });
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.ExerciseEquipment", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("char(36)");

                    b.HasKey("ExerciseId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ExerciseEquipment", (string)null);
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.ExerciseExerciseCategory", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ExerciseCategoryId")
                        .HasColumnType("char(36)");

                    b.HasKey("ExerciseId", "ExerciseCategoryId");

                    b.HasIndex("ExerciseCategoryId");

                    b.ToTable("ExerciseExerciseCategories", (string)null);
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.ExerciseMuscleGroup", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.HasKey("ExerciseId", "MuscleGroup");

                    b.ToTable("ExerciseMuscleGroups", (string)null);
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.SessionExerciseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("WorkoutExerciseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("SessionExerciseLogs", (string)null);
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.SessionSetLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("ActualDistanceMeters")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int?>("ActualDurationSeconds")
                        .HasColumnType("int");

                    b.Property<short?>("ActualReps")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("ActualWeightKg")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<byte?>("Rpe")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("SessionExerciseLogId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<int>("SetType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionExerciseLogId");

                    b.ToTable("SessionSetLogs", (string)null);
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkoutTemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutDays", (string)null);
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<short?>("RestDurationSeconds")
                        .HasColumnType("smallint");

                    b.Property<Guid>("WorkoutDayId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("WorkoutExercises", (string)null);
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutExerciseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<int>("SetType")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetDistanceMeters")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("int");

                    b.Property<short?>("TargetReps")
                        .HasColumnType("smallint");

                    b.Property<byte?>("TargetRpe")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("WorkoutExerciseSets", (string)null);
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("WorkoutDayId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutDayId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("WorkoutSessions", (string)null);
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutTemplates", (string)null);
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.ExerciseEquipment", b =>
                {
                    b.HasOne("Fithub.Platform.Domain.Workout.Equipment", "Equipment")
                        .WithMany("Exercises")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fithub.Platform.Domain.Workout.Exercise", "Exercise")
                        .WithMany("Equipment")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.ExerciseExerciseCategory", b =>
                {
                    b.HasOne("Fithub.Platform.Domain.Workout.ExerciseCategory", "ExerciseCategory")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fithub.Platform.Domain.Workout.Exercise", "Exercise")
                        .WithMany("Categories")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("ExerciseCategory");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("Fithub.Platform.Domain.Workout.Exercise", "Exercise")
                        .WithMany("MuscleGroups")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.SessionExerciseLog", b =>
                {
                    b.HasOne("Fithub.Platform.Domain.Workout.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fithub.Platform.Domain.Workout.WorkoutExercise", "WorkoutExercise")
                        .WithMany()
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fithub.Platform.Domain.Workout.WorkoutSession", "WorkoutSession")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutExercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.SessionSetLog", b =>
                {
                    b.HasOne("Fithub.Platform.Domain.Workout.SessionExerciseLog", "SessionExerciseLog")
                        .WithMany("SetLogs")
                        .HasForeignKey("SessionExerciseLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionExerciseLog");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutDay", b =>
                {
                    b.HasOne("Fithub.Platform.Domain.Workout.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Days")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutExercise", b =>
                {
                    b.HasOne("Fithub.Platform.Domain.Workout.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fithub.Platform.Domain.Workout.WorkoutDay", "WorkoutDay")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutExerciseSet", b =>
                {
                    b.HasOne("Fithub.Platform.Domain.Workout.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutSession", b =>
                {
                    b.HasOne("Fithub.Platform.Domain.Workout.WorkoutDay", "WorkoutDay")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.Equipment", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.Exercise", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Equipment");

                    b.Navigation("MuscleGroups");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.ExerciseCategory", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.SessionExerciseLog", b =>
                {
                    b.Navigation("SetLogs");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutDay", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutSession", b =>
                {
                    b.Navigation("ExerciseLogs");
                });

            modelBuilder.Entity("Fithub.Platform.Domain.Workout.WorkoutTemplate", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
