<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
	<PackageReference Include="FluentAssertions" Version="8.2.0" />
	<PackageReference Include="FluentMigrator" Version="7.1.0" />
	<PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
	<PackageReference Include="FluentMigrator.Runner.MySql" Version="7.1.0" />
	<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.14" />
	<PackageReference Include="Respawn" Version="6.2.1" />
	<PackageReference Include="Testcontainers" Version="4.4.0" />
	<PackageReference Include="Testcontainers.MySql" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>