version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fithub_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fithub
      MYSQL_PASSWORD: Testing99
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
