name: Build on Push to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # Change to your project version

      - name: Restore dependencies
        run: dotnet restore --verbosity detailed

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Testing with the dotnet CLI
        run: dotnet test --no-build
